#kivy 1.8.0
#:import MeshLinePlot kivy.garden.graph.MeshLinePlot

<DataWidget>
	GridLayout:
		cols: 1
		size_hint: 1,1
		col_default_width: 1500
		GridLayout:
			cols: 4
			size_hint: 1, 1
			col_default_width: 200
			row_default_height: root.height/8
			top: root.top
			Label:
				text: 'Field'
				size: self.texture_size
			Label:
				text: 'Value'
				size: self.texture_size
			Label:
				text: 'Max'
				size: self.texture_size
			Label:
				text: 'Graph'
				size: self.texture_size
			Label:
				text: 'Acceleration X, Y, Z'
				size: self.texture_size
			Label:
				text: root.accel
				size: self.texture_size
			Label:
				text: root.accelMax
				size: self.texture_size
			Graph:
				id: graph_accel
				xlabel:'Time'
				ylabel:'Accel'
				y_grid_label: True
				x_grid_label: True
				padding: 5
				xmin:0
				xmax:100
				ymin:-10
				ymax:10
				
			Label:
				text: 'Altitude'
				size: self.texture_size
			Label:
				text: str(root.altitude)
				size: self.texture_size
			Label:
				text: str(root.altitudeMax)
				size: self.texture_size
			Graph:
				id: graph_alt
				xlabel:'Time'
				ylabel:'Alt'
				y_grid_label: True
				x_grid_label: True
				padding: 5
				xmin:0
				xmax:100
				ymin:0
				ymax:5000
				
			Label:
				text: 'Coordinates'
				size: self.texture_size
			Label:
				text: root.coordinates
				size: self.texture_size
			Label:
				text: "NA"
				size: self.texture_size
			Graph:
				id: graph_coord
				xlabel:'Time'
				ylabel:'latlon'
				y_grid_label: True
				x_grid_label: True
				padding: 5
				xmin:0
				xmax:100
				ymin:0
				ymax:5000
				
			Label:
				text: 'GPS Speed'
				size: self.texture_size
			Label:
				text: str(root.gpsSpeed)
				size: self.texture_size
			Label:
				text: str(root.gpsSpeedMax)
				size: self.texture_size
			Graph:
				id: graph_gpsspeed
				xlabel:'Time'
				ylabel:'speed'
				y_grid_label: True
				x_grid_label: True
				padding: 5
				xmin:0
				xmax:100
				ymin:0
				ymax:5000
				
			Label:
				text: 'status'
				size: self.texture_size
			Label:
				text: root.status
				size: self.texture_size
			
		
		BoxLayout:
			id: buttons
			orientation: 'horizontal'
			Button:
				text: 'start recording'
				on_press: app.pressButton('r')
			Button:
				text: 'start/stop transmitting'
				on_press: app.pressButton('s')
			Button:
				text: 'pause SD'
				on_press: app.pressButton('p')
			Button:
				text: 'RESTART'
				on_press: app.pressButton('a')
			Button:
				text: 'list files'
				on_press: app.pressButton('L')
			Button:
				text: 'start buzzer'
				on_press: app.pressButton('b')
			Button:
				text: 'stop buzzer'
				on_press: app.pressButton('B')
